# Copyright (C) 2022 Dremio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Projectnessie GitHub Pull-Request / macOS CI

name: Windows Build Check

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  schedule:
    # Run daily on week days
    - cron:  '0 4 * * 1-5'
  workflow_dispatch:

# For the main branch: let all CI runs complete, one after the other. This has a couple advantages:
# * Site deployments happen in commit-order
# * Saved Gradle cache are persisted in commit-order
# * (Potentially) more GH runners available for PRs
concurrency:
  # PRs: 1 CI run concurrently / older ones are cancelled
  # main branch: 1 CI run concurrently / all commits / no cancellation
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  java:
    name: Java/Gradle Windows
    runs-on: windows-2022
    timeout-minutes: 60
    if: (github.repository == 'projectnessie/nessie' && github.event_name != 'pull_request') || contains(github.event.pull_request.labels.*.name, 'pr-macos-win')
    env:
      SPARK_LOCAL_IP: localhost

    steps:
    - name: Git line ending config
      # This is a workaround to pass the ui/ project's prettier configuration, which has the strict
      # rule to allow only LF as the line ending.
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        repository: cdarlint/winutils
        path: hadoop-winutils
        ref: d018bd9c919dee1448b95519351cc591a6338a00

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Setup Java, Gradle
      uses: ./.github/actions/dev-tool-java

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@d9336dac04dea2507a617466bc058a3def92b18b # v3
      env:
        # Same as for ci.yml
        GRADLE_BUILD_ACTION_CACHE_KEY_ENVIRONMENT: java-17
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB: nessie-ci
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB_INSTANCE: ci
      with:
        cache-read-only: true

    - name: Gradle / compile
      run: ./gradlew assemble --scan
